[build]
  base = "."
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cloudinary" # ../../ wont work for local install

  [plugins.inputs]
  cloudName = "colbycloud"
  # deliveryType = "upload"